services:
  miniblog:
    build: .
    image: miniblog:latest
    container_name: miniblog
    ports:
      - "4321:4321"
    volumes:
      - miniblog_data:/app/data
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=production
      - DB_FILENAME=data/miniblog.db
      - HOST=0.0.0.0
      - PORT=4321
      - ORIGIN=http://localhost:4321
    restart: unless-stopped

volumes:
  miniblog_data: